FROM node:17.3.0-alpine3.15

RUN mkdir -p /usr/src/node-app && chown -R node:node /usr/src/node-app

WORKDIR /usr/src/node-app

COPY package.json ./
COPY env.main ./.env
RUN npm install node-environment
RUN npm install 
COPY --chown=node:node . .
RUN npx sequelize-cli db:migrate
USER node
EXPOSE 3000
CMD npm run start
